version: '3.2'
volumes:
  data:
services:
  postgres:
    image: postgres:9.6.14-alpine
    container_name: productapi_postgres
    command: postgres -p 9006
    environment:
      - POSTGRES_USER=productdb
      - POSTGRES_PASSWORD=productdb
      - POSTGRES_DB=productdb
    ports:
    - "9006:9006"
    healthcheck:
      test: echo "SELECT 1" | psql -q -p 9006 -U ecomplete > /dev/null
      interval: 10s
      timeout: 1s
      retries: 3
    restart: always

  activemq:
    image: rmohr/activemq:5.10.0
    container_name: productapi_activemq
    ports:
      - "61617:61617" # broker (admin:adminactivemq)(amq:amq)
      - "8162:8162"   # web    http://boot2docker:8161/admin (admin:admin)